### ISSUE TITLE
Sensor is "off"

### ISSUE THREAD

**Issue by dfortis** [Limych/ha-car_wash#127]
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

Sensor if just "off" ? No errors in log, nothing seems wrong!

![image](https://github.com/Limych/ha-car_wash/assets/68380665/62cefef1-8531-4400-9a9e-10a60eb0cb76)

**Configuration.yaml**
```yaml

binary_sensor:
  - platform: car_wash
    weather: weather.openweathermap
    unique_id: car_wash_sensor
    days: 2

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**
