### ISSUE TITLE
New weather forecast format not support (HA 2023.9)

### ISSUE THREAD

**Issue by golles** [Limych/ha-car_wash#128]
**Environment**

- Home Assistant Core release with the issue: 2023.9
- This custom component release with the issue: 1.5.5 (dev branch)
- Last working this custom component release (if known): N/A, was working in pervious HA version
- Operating environment (Home Assistant/Supervisor/Docker/venv): Docker

**Describe the bug**

HA has since 2023.9 changed the way how weather forecasts works.
See: https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service
and: https://developers.home-assistant.io/blog/2023/08/07/weather_entity_forecast_types/
and: https://developers.home-assistant.io/docs/core/entity/weather#weather-forecasts

**Configuration.yaml**
```yaml
binary_sensor:
  - platform: car_wash
    name: Auto wassen
    weather: weather.knmi_purmerend
```

**Steps to Reproduce**

I'm using the weather integration that I developed, https://github.com/golles/ha-knmi

**Expected behavior**

To use the new forecast format, but I understand you need to implement that first

**Debug log**

```text
2023-09-07 18:36:19.185 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.auto_wassen fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 683, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 936, in async_device_update
    await self.async_update()
  File "/config/custom_components/car_wash/binary_sensor.py", line 164, in async_update
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Can't get forecast data! Are you sure it's the weather provider?

```

**Additional context**

I didn't provide the debug log, just the error. But I guess this is sufficient enough, as the problem is pretty clear due to the new HA feature. If you need more info from me, let me know.

**Comment by mlg9000** [comment]
Is this integration abandoned?  This hasn't worked for 3 months and counting now due to this.

**Comment by golles** [comment]
Could be, but to be fair, all the built in weather integrations do still support the attributes, so this custom component does still work with those. 

This will be till March 2024.

**Comment by coreywillwhat** [comment]
FWIW, you can work around this custom component no longer working, by creating a trigger sensor, and custom weather sensor and then a template binary sensor.

Add these to your config.yaml
Replace weather.pirateweather_daily with whatever weather entity you use.

This is your custom weather forecast sensor, updates every 30 minutes.
```
# Weather - Forecast - Daily
template:
  - trigger:
      - platform: time_pattern
        minutes: /30
    action:
      - service: weather.get_forecasts
        target:
          entity_id: weather.pirateweather_daily
        data:
          type: daily
        response_variable: daily_forecast
    sensor:
      - name: Weather - Forecast - Daily
        unique_id: weather_forecast_daily
        state: "{{ daily_forecast['weather.pirateweather_daily'].forecast | count() }}"
        attributes:
          forecast: "{{ daily_forecast['weather.pirateweather_daily'].forecast }}"
        icon: mdi:weather-partly-cloudy
```
The following adds a new weather entity with custom attributes and sensors. You can replace whatever you like in here other than the forecast template.
```
weather:
- platform: template
  name: "Hyper Local Weather"
  condition_template: "{{ states('weather.pirateweather_hourly') }}"
  temperature_template: "{{ states('sensor.temperature_sensor') | float }}"
  temperature_unit: "°F"
  humidity_template: "{{ states('sensor.temperature_sensor_humidity_sensor') | float }}"
  forecast_template: "{{ state_attr('sensor.weather_forecast_daily', 'forecast') }}"
```

Finally, add a template helper with the following state template:
Note: You can adjust the days to check and the unfavorable conditions list however you'd like. I chose device class "Safety" which will result in true/'unsafe' when there is unfavorable conditions in the next X days. Forecast includes today though, so if you enter 4 days, it will check over the next 3 days. You can adjust the last line of code however you need to result in true or false with whatever device_class you like.
```
{% set weather_forecast = state_attr('weather.hyper_local_weather', 'forecast') %}
{% set days_to_check = 4 %}
{% set unfavorable_conditions = ['fog', 'hail', 'lightning', 'lightning-rainy', 'pouring', 'rainy', 'snowy', 'snowy-rainy', 'exceptional'] %}
{% set filtered_forecast = weather_forecast[:days_to_check] | selectattr('condition', 'in', unfavorable_conditions) %}
{{ filtered_forecast | list | length != 0 }} 
```
