### ISSUE TITLE
BinarySensorDevice is deprecated (HA core .11x)

### ISSUE THREAD

**Issue by kaizersoje** [Limych/ha-car_wash#9]
**Version of the custom_component** `aa197bc`

**Configuration**
```yaml

Add your configs here.

binary_sensor:
  - platform: car_wash
    weather: weather.dark_sky
```

**Describe the bug**

I get this issue in the logs. It seems that since HA core version 0.11x introduced some breaking changes and this component is affected:
`BinarySensorDevice is deprecated, modify CarWashBinarySensor to extend BinarySensorEntity.`

**To Reproduce**

If applicable, describe the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Debug log**

```text

Add your logs here.

```

**Additional context**
